LOOKBACK_PERIOD = 60

NSE_TICKERS = [
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS',
    'HINDUNILVR.NS', 'BHARTIARTL.NS', 'ITC.NS', 'SBIN.NS', 'LT.NS',
    'BAJFINANCE.NS', 'ASIANPAINT.NS', 'KOTAKBANK.NS', 'AXISBANK.NS',
    'SUNPHARMA.NS', 'MARUTI.NS', 'ULTRACEMCO.NS', 'NESTLEIND.NS',
    'WIPRO.NS', 'TECHM.NS', 'HCLTECH.NS', 'INDUSINDBK.NS', 'TITAN.NS',
    'ADANIPORTS.NS', 'GRASIM.NS', 'POWERGRID.NS', 'NTPC.NS', 'ONGC.NS',
    'COALINDIA.NS', 'IOC.NS', 'BPCL.NS', 'GAIL.NS', 'MM.NS', 'HEROMOTOCO.NS',
    'DRREDDY.NS', 'CIPLA.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'BRITANNIA.NS',
    'EICHERMOT.NS', 'JSWSTEEL.NS', 'TATAMOTORS.NS', 'TATASTEEL.NS',
    'HDFCLTD.NS', 'BAJAJFINSV.NS', 'DIVISLAB.NS', 'APOLLOHOSP.NS',
    'BANDHANBNK.NS', 'PIDILITIND.NS', 'DMART.NS'
]
